name: compile
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.tex'
permissions:
  contents: write
jobs:          
  latexmk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          # XXX Emacs 26.1's make install doesn't install emacs-module.h
          # - 26.1
          # - 26.3
          - snapshot
    steps:
      - name: Checkout pages
        uses: actions/checkout@v3
        with:
          ref: deploy
          fetch-depth: 0
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      - name: Debugging shell        
        working-directory: ${{ env.DIR }}
        run: |
          echo "Current directory is $(pwd)"
          echo "Listing files in the current directory:"
          ls -al
          echo "Git status:"
          git status
          echo "Git branch:"
          git branch
      - name: Rebase from main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git rebase origin/main
      - name: Debugging shell
        working-directory: ${{ env.DIR }}
        run: |
          echo "Current directory is $(pwd)"
          echo "Listing files in the current directory:"
          ls -al
      - name: Run latexmk
        run: |
          EXCLUDE_FILES=$(jq -r '.exclude[]' config.json | tr '\n' '|' | sed 's/.$//')
          if [[ "${{ github.event_name }}" == "push" ]]; then          
            git diff --name-only --diff-filter=d ${{ github.event.before }} ${{ github.event.after }} | grep .tex | grep -vE $EXCLUDE_FILES | while read file; do
              ./compile.sh $file
            done
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            git ls-files "*.tex" | grep -vE $EXCLUDE_FILES | while read file; do
              ./compile.sh $file
            done
          fi
      - name: Debugging shell        
        working-directory: ${{ env.DIR }}
        run: |
          echo "Current directory is $(pwd)"
          echo "Listing files in the current directory:"
          ls -al
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Convert to html
        run: |
          EXCLUDE_FILES=$(jq -r '.exclude[]' config.json | tr '\n' '|' | sed 's/.$//')
          if [[ "${{ github.event_name }}" == "push" ]]; then
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep .tex | grep -vE $EXCLUDE_FILES | while read file; do
              ./convert.sh $file
            done
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            git ls-files "*.tex" | grep -vE $EXCLUDE_FILES | while read file; do
              ./convert.sh $file
            done
          fi            
      - name: Debugging shell        
        working-directory: ${{ env.DIR }}
        run: |
          echo "Current directory is $(pwd)"
          echo "Listing files in the current directory:"
          ls -al
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.txt
          git add *.aux || true
          git add *.pdf || true
          git add *.html || true
          git commit -m "Updated aux, pdf and html files" || echo "No changes to commit"
          git push -f
