name: Update Recent Comments
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: deploy
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install axios
      - name: Rebase from main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git rebase origin/main
      - name: Generate recent comments page
        run: node generate-comments-page.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Debugging shell        
        working-directory: ${{ env.DIR }}
        run: |
          echo "Current directory is $(pwd)"
          echo "Listing files in the current directory:"
          ls -al
          echo "Git status:"
          git status
          echo "Git branch:"
          git branch
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add recent-discussions.json
          git commit -m "Update recent comments page" || exit 0
          git push
